# Generated by Django 4.1.5 on 2023-01-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadManagementApp', '0004_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateid', models.IntegerField()),
                ('cityid', models.IntegerField()),
                ('cityname', models.CharField(default='', max_length=45)),
            ],
        ),
    ]
